#pragma once

#include <arch/page.h>

#define KERNEL_SPACE_START ARCH_KERNEL_SPACE_START
#define KERNEL_SPACE_END ARCH_KERNEL_SPACE_END
#define KERNEL_SECTIONS_SPACE_START ARCH_KERNEL_SECTIONS_SPACE_START
#define KERNEL_SECTIONS_SPACE_END ARCH_KERNEL_SECTIONS_SPACE_END
#define USER_SPACE_START ARCH_USER_SPACE_START
#define USER_SPACE_END ARCH_USER_SPACE_END

#define PAGE_SHIFT ARCH_PAGE_SHIFT
#define PMD_SHIFT ARCH_PMD_SHIFT
#define PUD_SHIFT ARCH_PUD_SHIFT
#define PAGE_SIZE (1ul << PAGE_SHIFT)
#define PMD_SIZE (1ul << PMD_SHIFT)
#define PUD_SIZE (1ul << PUD_SHIFT)

typedef enum {
	PGPROT_NONE = (1 << 0),
	PGPROT_READ = (1 << 1),
	PGPROT_WRITE = (1 << 2), 
	PGPROT_USER = (1 << 3),
	PGPROT_EXEC = (1 << 4),
	PGPROT_WB = (0b00 << 5),
	PGPROT_WT = (0b01 << 5),
	PGPROT_UC = (0b10 << 5),
	PGPROT_WC = (0b11 << 5)
} pgprot_t;

#define PGPROT_CACHE_MASK (PGPROT_WB | PGPROT_WT | PGPROT_UC | PGPROT_WC)
#define PGPROT_MASK (PGPROT_NONE | PGPROT_READ | PGPROT_WRITE | PGPROT_USER | PGPROT_EXEC | PGPROT_CACHE_MASK)
